### ISSUE TITLE
yast-iscsi-client assumes iscsi commands will be in /sbin

### ISSUE THREAD

**Issue by gonzoleeman** [yast/yast-iscsi-client#111]
The iscsi commands are moving from /sbin to /usr/sbin, as per a factory requirement (the "usr merge" project).

The open-iscsi package has already moved binaries from /sbin to /usr/sbin in SLE-15-SP3:Update and SLE-15-SP4 (which currently uses the same package).

The code in yast-iscsi-client needs to either assume the binaries will be in /usr/sbin, or it needs to use the PATH variable, or it needs to check for where the commands are actually located.

I can certainly submit a pull request for the proper branches to do the straight substitution, but I'm not familiar enough with Ruby to offer to handle anything fancier.

**Comment by kobliha** [comment]
I'm now checking https://build.opensuse.org/package/view_file/SUSE:SLE-15-SP3:Update/open-iscsi/open-iscsi.changes?expand=1 and https://build.opensuse.org/request/show/927854 -- it seems SLE is actually not affected, only openSUSE. And sadly, I haven't seen any openSUSE-related issues yet. Does it mean it's not used there?

**Comment by gonzoleeman** [comment]
> I'm now checking https://bugzilla.suse.com/show_bug.cgi?id=1192013 and https://build.opensuse.org/request/show/927854 -- it seems SLE is actually not affected, only openSUSE. And sadly, I haven't seen any openSUSE-related issues yet. Does it mean it's not used there?

Correct -- so far, only openSUSE Tumbleweed is effected, as they are the ones that made the new rule that everything in /sbin should be in /usr/sbin. But the RPM is smart enough to know when it's being built for Tumbleweed.

But "soon" this change will come to SLE, and it seems like these paths should not be hard-coded into yast, IMHO. It seems like Yast should either use PATH, or search for commands using PATH. I assume there are many other hard-coded paths in Yast, so this kind of change would only make it more robust. Yast could even set it's own PATH, if it wished, to ensure security.

**Comment by ancorgs** [comment]
> But "soon" this change will come to SLE, and it seems like these paths should not be hard-coded into yast, IMHO. It seems like Yast should either use PATH, or search for commands using PATH. I assume there are many other hard-coded paths in Yast, so this kind of change would only make it more robust. Yast could even set it's own PATH, if it wished, to ensure security.

Actually YaST switched to using hard-coded full paths everywhere by advise of the SUSE Security Team. The YaST source code was audited on November 2018 and one of the advises the developers got from the security experts was to use absolute paths. You can see [quite some changes in YaST](https://github.com/search?q=org%3Ayast+bsc%231118291&type=code) around that date to accommodate to that.

**Comment by gonzoleeman** [comment]
> > But "soon" this change will come to SLE, and it seems like these paths should not be hard-coded into yast, IMHO. It seems like Yast should either use PATH, or search for commands using PATH. I assume there are many other hard-coded paths in Yast, so this kind of change would only make it more robust. Yast could even set it's own PATH, if it wished, to ensure security.
> 
> Actually YaST switched to using hard-coded full paths everywhere by advise of the SUSE Security Team. The YaST source code was audited on November 2018 and one of the advises the developers got from the security experts was to use absolute paths. You can see [quite some changes in YaST](https://github.com/search?q=org%3Ayast+bsc%231118291&type=code) around that date to accommodate to that.

Heh. That's why security folks don't get to design software. That's a safe but dumb approach IMHO. (I used to work in security, so it's okay for me to say this is dumb.)

Yast could simply set it's own PATH to something like "/bin:/usr/bin:/usr/bin:/sbin:/etc".

Or, if they want to be pedantic (evidently, they like that), they could actually find the binaries they need, looking only in approved directories (like those I listed), and remembering the path.

Of course it's easier to just hard-code it. But then when things move, you have a problem.

The problem IMHO is that the path of a binary is not part of its API. So the path can change any time, at the whim of the system administrators and package designers. Using hard-coded paths makes yast very brittle.

Please feel free to close this issue if you choose not to address this. Or perhaps mark it as an enhancement request. :)

**Comment by ancorgs** [comment]
> Please feel free to close this issue if you choose not to address this. Or perhaps mark it as an enhancement request. :)

Actually, I think the most productive thing to do would be bringing those who recommended fixed paths into the discussion. So, @jsegitz, any remark?

**Comment by Vogtinator** [comment]
The main (only?) benefit of hardcoding paths (or `$PATH`, for that matter) would be to avoid that some custom compiled binaries from `/usr/local`, `/opt` or elsewhere are used. That's arguably also an anti-feature though if the replacement is intentional...

**Comment by wfeldt** [comment]
The starting point was the `/sbin` -> `/usr/sbin` move which is actually a non-issue as the compat symlinks will stay in place for the forseeable future (aka 'forever').

And the discussion over $PATH vs. calling with full path is as old as is $PATH. Both are technically equivalent, the drawback of using $PATH is that you have to ensure it's actrually set correctly all the time. That's relatively easy for a small go binary, for example, but more challanging for a distributed code base as yast.

**Comment by shundhammer** [comment]
> Yast could simply set it's own PATH to something like "/bin:/usr/bin:/usr/sbin:/sbin:/etc".

Yes, that was _exactly_ our argument back some years ago when we had to go over all our YaST code after that security audit and change every single call to an external program to use the full path.

We predicted that this alledgedly enhanced security would turn into a total DoS if ever any of those binaries were moved to a different location. But we were overruled.

Fast forward 3 (or so) years to today, and that's exactly what happened.

So _please_ let's fix that now once and for all. The infrastructure exists since the early 1970s: It's `$PATH` and invoking external binaries just with their name and letting the system find the exact location.

Of course we need a well-defined `$PATH`; one that doesn't contain known security hazards like `.` for the current directory, or any directory that commonly has write access to non-privileged users (so some user could dump malicious code there). I have yet to hear a true argument against that approach.

**Comment by shundhammer** [comment]
> The main (only?) benefit of hardcoding paths (or `$PATH`, for that matter) would be to avoid that some custom compiled binaries from `/usr/local`, `/opt` or elsewhere are used. That's arguably also an anti-feature though if the replacement is intentional...

The main argument for a well-defined fixed `$PATH` are admins who add known security hazards like `.` or directories that have write access to non-privileged users to it because of convenience or because they don't know any better.

Within our area of responsibility we need to take great care not to make that too easy; any security problems will reflect on our products.

**Comment by ancorgs** [comment]
We also introduced this change back then, which AFAICS (and I'm not an expert at all) ensures that proper $PATH: https://github.com/yast/yast-ruby-bindings/pull/223

**Comment by shundhammer** [comment]
Master bug for this in Bugzilla:

https://bugzilla.suse.com/show_bug.cgi?id=1196085

A specific one for the iscsi tools will follow.

**Comment by suntorytimed** [comment]
It's important to note that open-iscsi didn't move the iscsi binaries to /usr/sbin in 15 SP3 Update and 15 SP4 GA. There is a switch in the spec file, which packages all SLE versions with /sbin. This is also the expected behaviour of all packages coming from Factory that are already usr-merged. They require specific handling for a non usr-merged environment like SLE (https://en.opensuse.org/openSUSE:Usr_merge#Packaging). SLE-15 won't get usr-merged and usr-merged applications shouldn't move their binaries to /usr in SLE.

**Comment by shundhammer** [comment]
I collected some information about how external binaries are called in YaST:
https://gist.github.com/shundhammer/382faaae5371087e7afb13007510c6d5
(temporary location, this will eventually go to a `doc/` directory of one of our YaST repos)

**Comment by shundhammer** [comment]
Summarizing the situation that this issue was originally all about: The location of iSCSI binaries (package _open-iscsi_):

- `/sbin` in SLE-15 SP4/SP3/SP2/SP1/GA
- `/sbin` in Leap 15.x
- `/usr/sbin` in TW

But in TW, there are still those compatibility symlinks `/bin` -> `/usr/bin` and `/sbin` -> `/usr/sbin`, i.e. those iSCSI tools are also available via `/sbin`.

And as @wfeldt wrote above, it is very unlikely that they will be removed in the forseeable future: Too many third-party scripts and programs would break, starting with each and every shell script with a `#!/bin/sh` she-bang.

Still, I'd like to make sure, not make assumptions, so I would very much prefer to migrate this to invoking external binaries via `$PATH` instead of using the absolute path for each one of them.

**Comment by shundhammer** [comment]
The security audit summary back then: https://github.com/yast/yast.github.io/issues/172

**Comment by shundhammer** [comment]
PR #113 is now merged, so I am now closing this.
